[task1.zhwiki]

inpath = "/mnt/samba_shared/wyw/code/中电科_分类/data/domain_and_region/zhwiki/1/*.jsonl.zst"
read_batch_size = 80
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_thinking"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_org.txt"

[task1.enwiki]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/raw/enwiki/*.jsonl.zst"
read_batch_size = 80
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_thinking"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_org.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = [
    "/Data_two/wyw/code/CETC_product/data/out/task1/enwiki/20251117_000108"
]

[task2.zhwiki]
inpath = "/mnt/samba_shared/wyw/code/中电科_分类/data/domain_and_region/zhwiki/1/*.jsonl.zst"
read_batch_size = 80
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_thinking"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_person.txt"


[task2.enwiki]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/raw/enwiki/0.jsonl.zst"
read_batch_size = 160
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "qwen_plus"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_person.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = [
    "/Data_two/wyw/code/CETC_product/data/out/task2/enwiki/20251117_151015"
]
