[task1.zhwiki]

inpath = "/mnt/samba_shared/wyw/code/中电科_分类/data/domain_and_region/zhwiki/1/*.jsonl.zst"
read_batch_size = 200
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "qwen_flash"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_org.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = "/Data_two/wyw/data/CETC_PRODUCT/task1/zhwiki_*"


[task1.enwiki]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/raw/enwiki/*.jsonl.zst"
read_batch_size = 300
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "gpt_low"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_org.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = "/Data_two/wyw/code/CETC_product/data/out/task1/enwiki/*"

[task2.zhwiki1]
inpath = "/mnt/samba_shared/wyw/code/中电科_分类/data/domain_and_region/zhwiki/1/[0-2].jsonl.zst"
read_batch_size = 700
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_flash"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_wiki_person.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = ["/Data_two/wyw/code/CETC_product/data/out/task2/zhwiki/*", "/Data_two/wyw/code/CETC_product/data/out/task2/zhwiki1/*"]

[task2.zhwiki2]
inpath = "/mnt/samba_shared/wyw/code/中电科_分类/data/domain_and_region/zhwiki/1/[3-4].jsonl.zst"
read_batch_size = 700
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_lite_low"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_wiki_person.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = ["/Data_two/wyw/code/CETC_product/data/out/task2/zhwiki/*", "/Data_two/wyw/code/CETC_product/data/out/task2/zhwiki2/*"]

[task2.enwiki1]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/raw/enwiki/{0..8}.jsonl.zst"
read_batch_size = 800
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "gpt_low"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_wiki_person.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = [
    "/Data_two/wyw/code/CETC_product/data/out/task2/enwiki/*",
    "/Data_two/wyw/code/CETC_product/data/out/task2/enwiki1/*"
    ]


[task2.enwiki2]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/raw/enwiki/{9..18}.jsonl.zst"
read_batch_size = 600
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_flash_auth"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_wiki_person.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = [
    "/Data_two/wyw/code/CETC_product/data/out/task2/enwiki/*",
    "/Data_two/wyw/code/CETC_product/data/out/task2/enwiki2/*"
    ]


[task2.enwiki3]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/raw/enwiki/{18..26}.jsonl.zst"
read_batch_size = 600
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_lite_low_auth"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_wiki_person.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = [
    "/Data_two/wyw/code/CETC_product/data/out/task2/enwiki/*",
    "/Data_two/wyw/code/CETC_product/data/out/task2/enwiki3/*"
    ]


[task3.splite1]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/task3/raw/splited/part_00.jsonl.zst"
read_batch_size = 600
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_seed_low_auth"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_social.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = [
    "/Data_two/wyw/code/CETC_product/data/out/task3/splite1/*",
    ]

[task3.splite2]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/task3/raw/splited/part_01.jsonl.zst"
read_batch_size = 1000
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_flash"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_social.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = [
    "/Data_two/wyw/code/CETC_product/data/out/task3/splite2/*"
    ]

[task3.splite3]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/task3/raw/splited/part_02.jsonl.zst"
read_batch_size = 600
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_lite_low_auth"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_social.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = [
    "/Data_two/wyw/code/CETC_product/data/out/task3/splite3/*"
    ]


[task5.splite1]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/task5/raw/splited/part_00.jsonl.zst"
read_batch_size = 1000
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_lite_low_auth"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_event.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = ["/Data_two/wyw/code/CETC_product/data/out/task5/total/*"]

[task5.splite2]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/task5/raw/splited/part_01.jsonl.zst"
read_batch_size = 1000
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_flash_auth"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_event.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = ["/Data_two/wyw/code/CETC_product/data/out/task5/total/*"]

[task5.splite3]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/task5/raw/splited/part_0{2..3}.jsonl.zst"
read_batch_size = 1000
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_seed_low"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/NER_for_event.txt"
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = ["/Data_two/wyw/code/CETC_product/data/out/task5/total/*"]


[domain_enhance.task1_batch1]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/domain_enhance_input/task1/0.jsonl"
read_batch_size = 1000
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_lite_low_auth"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/endance_for_domain.txt"
domain_enhance_map_path = "/Data_two/wyw/code/CETC_product/data/domain_map.json"            # 领域增强的独有参数，领域增强映射
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = "/Data_two/wyw/code/CETC_product/data/out/domain_enhance/task1_batch1/*"

[domain_enhance.task1_batch2]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/domain_enhance_input/task1/1.jsonl"
read_batch_size = 1000
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_flash"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/endance_for_domain.txt"
domain_enhance_map_path = "/Data_two/wyw/code/CETC_product/data/domain_map.json"            # 领域增强的独有参数，领域增强映射
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = "/Data_two/wyw/code/CETC_product/data/out/domain_enhance/task1_batch2/*"


[domain_enhance.task2_batch1]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/domain_enhance_input/task2/chunk_0.jsonl"
read_batch_size = 1000
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_lite_low"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/endance_for_domain.txt"
domain_enhance_map_path = "/Data_two/wyw/code/CETC_product/data/domain_map.json"            # 领域增强的独有参数，领域增强映射
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = "/Data_two/wyw/code/CETC_product/data/out/domain_enhance/task2_batch1/*"

[domain_enhance.task2_batch2]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/domain_enhance_input/task2/chunk_1.jsonl"
read_batch_size = 1000
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_flash_auth"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/endance_for_domain.txt"
domain_enhance_map_path = "/Data_two/wyw/code/CETC_product/data/domain_map.json"            # 领域增强的独有参数，领域增强映射
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = "/Data_two/wyw/code/CETC_product/data/out/domain_enhance/task2_batch2/*"


[domain_enhance.task2_batch3]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/domain_enhance_input/task2/chunk_2.jsonl"
read_batch_size = 1000
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_lite_low_auth"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/endance_for_domain.txt"
domain_enhance_map_path = "/Data_two/wyw/code/CETC_product/data/domain_map.json"            # 领域增强的独有参数，领域增强映射
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = "/Data_two/wyw/code/CETC_product/data/out/domain_enhance/task2_batch3/*"



[domain_enhance.task2_batch4]
inpath = "/Data_two/wyw/data/CETC_PRODUCT/domain_enhance_input/task2/chunk_3.jsonl"
read_batch_size = 1000
outpath = "/Data_two/wyw/code/CETC_product/data/out"
llm_name = "doubao_flash"
prompt_path = "/Data_two/wyw/code/CETC_product/data/prompts/endance_for_domain.txt"
domain_enhance_map_path = "/Data_two/wyw/code/CETC_product/data/domain_map.json"            # 领域增强的独有参数，领域增强映射
checkpoint_path = "/Data_two/wyw/code/CETC_product/data/checkpoints"
writed_data_paths = "/Data_two/wyw/code/CETC_product/data/out/domain_enhance/task2_batch4/*"


